[pytest]
python_files =

markers =
    positive: Тесты, которые проверяют корректное поведение функции
    negative: Тесты, которые проверяют некорректное поведение функции

mark.parametrize = ("input_str, expected", argnames, argvalues)





